name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        continue-on-error: true
      - if: failure()
        run: echo we did it
      