name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:
  test: 
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: exit 1
      - if: failure()
        run: echo we did it
      